spring.application.name=presence-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=8086
springdoc.api-docs.path=/api/presence/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html