server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - JwtAuthFilter

        - id: auth-oauth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /login/**

        - id: auth-swagger
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**
          filters:
            - JwtAuthFilter

        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/api/messages/**
          filters:
            - JwtAuthFilter

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
          filters:
            - JwtAuthFilter

        - id: presence-service
          uri: lb://PRESENCE-SERVICE
          predicates:
            - Path=/api/presence/**
          filters:
            - JwtAuthFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - JwtAuthFilter

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws/**
          
          metadata:
            response-timeout: 0
            connect-timeout: 0

      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

     
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /api/auth/v3/api-docs
      - name: room-service
        url: /api/rooms/v3/api-docs
      - name: message-service
        url: /api/messages/v3/api-docs
      - name: presence-service
        url: /api/presence/v3/api-docs
      - name: media-service
        url: /api/media/v3/api-docs
      - name: notification-service
        url: /api/notifications/v3/api-docs

logging:
  level:
    root: WARN