server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - JwtAuthFilter

        - id: auth-oauth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /login/**

        - id: auth-swagger
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**
          filters:
            - JwtAuthFilter

        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/api/messages/**
          filters:
            - JwtAuthFilter

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
          filters:
            - JwtAuthFilter

        - id: presence-service
          uri: lb://presence-service
          predicates:
            - Path=/api/presence/**
          filters:
            - JwtAuthFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - JwtAuthFilter

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/ws/**
          filters:
            - JwtAuthFilter

      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

     
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN