spring.application.name=chat-service
server.port=8085
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true
# eureka.instance.hostname=localhost
# eureka.instance.instance-id=${spring.application.name}:${server.port}
jwt.secret=${JWT_SECRET}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.main.allow-bean-definition-overriding=true
logging.level.com.talkifyx=DEBUG
springdoc.api-docs.path=/ws/v3/api-docs

server.forward-headers-strategy=framework
